sudo: required
services:
  - docker

## create a build for react client for testing
before_install:
   - docker build -t gauravsegan/react-test -f ./client/dev.Dockerfile ./client
   ## -t for tagging image, override filename with you dev.Dockerfile
   ## in the end give the build context by ./client

## run tests off the client build
script:
  - docker run -e CI=true gauravsegan/react-test npm test 
  ## -- --coverage is to make sure test script exit with a status code (either 0 or non zero)

## create production builds for all others now including client
after_success:
  - docker build -t drumster88/multi-client ./client
  - docker build -t drumster88/multi-nginx ./nginx
  - docker build -t drumster88/multi-server ./server
  - docker build -t drumster88/multi-worker ./worker

## login to docker hub using enviroment variables defined in travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

## push all prod ready build images to dockerhub
  - docker push drumster88/multi-client
  - docker push drumster88/multi-nginx
  - docker push drumster88/multi-server
  - docker push drumster88/multi-worker