version: '3'
services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

    ## express server
  api:
    depends_on:
      - postgres
    build: 
      dockerfile: dev.Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
      
      ## defining environment variables referring keys.js
      ## defaults are taken from dockerhub documentation for that image
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  ## for react app, creating a service ##
  client:
    build: 
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:  
      - /app/node_modules
      - ./client:/app
  
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: dev.Dockerfile
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
  
  nginx:
    restart: always
    ## this needs to be running all the time as this routes traffic to all 
    ## back nodes and we cannot afford it's outage
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports: 
      - '2500:80' ## map localhost port to port 80 for nginx










      

    
    
  
    
